name: kolibri_settings
description: "Kolibri Settings - Standalone settings manager for Hypr Flutter panel"
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.3.3
  path: ^1.9.0
  file_picker: ^8.1.4
  flutter_colorpicker: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
